# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10FScJt9SUNuV13n3VGgb53BKj-_oAClN
"""

import random

def play_game():
    secret_number = random.randint(1, 100)
    attempts = 0
    max_attempts = 5

    print("\n🎲 Welcome to the Number Guessing Game!")
    print("I'm thinking of a number between 1 and 100...")
    print(f"You have {max_attempts} attempts. Good luck!")

    while attempts < max_attempts:
        guess = input("Enter your guess: ")

        if not guess.isdigit():
            print("⚠️ Please enter a valid number!")
            continue

        guess = int(guess)
        attempts += 1

        if guess < secret_number:
            print("Too low!")
        elif guess > secret_number:
            print("Too high!")
        else:
            print(f"🎉 Correct! You guessed it in {attempts} tries.")
            break

        # Bonus hint
        if abs(guess - secret_number) <= 5:
            print("🔍 Hint: You're very close!")

        print(f"Attempts left: {max_attempts - attempts}")

    else:
        print(f"❌ Out of attempts! The number was {secret_number}.")

# Play again loop
while True:
    play_game()
    again = input("Do you want to play again? (yes/no): ").lower()
    if again != 'yes':
        print("👋 Thanks for playing! Goodbye.")
        break

import random

def play_game():
    secret_number = random.randint(1, 100)
    attempts = 0
    max_attempts = 5

    print("\n🎲 Welcome to the Number Guessing Game!")
    print("I'm thinking of a number between 1 and 100...")
    print(f"You have {max_attempts} attempts. Good luck!")

    while attempts < max_attempts:
        guess = input("Enter your guess: ")

        if not guess.isdigit():
            print("⚠️ Please enter a valid number!")
            continue

        guess = int(guess)
        attempts += 1

        if guess < secret_number:
            print("Too low!")
        elif guess > secret_number:
            print("Too high!")
        else:
            print(f"🎉 Correct! You guessed it in {attempts} tries.")
            break

        # Bonus hint
        if abs(guess - secret_number) <= 5:
            print("🔍 Hint: You're very close!")

        print(f"Attempts left: {max_attempts - attempts}")

    else:
        print(f"❌ Out of attempts! The number was {secret_number}.")

# Play again loop
while True:
    play_game()
    again = input("Do you want to play again? (yes/no): ").lower()
    if again != 'yes':
        print("👋 Thanks for playing! Goodbye.")
        break

A

